//#pragma config(Sensor, S4,     Beacon,         sensorEV3_IRSensor, modeEV3IR_Seeker)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void configureAllSensors()
{

	SensorType[S1] = sensorEV3_Color;
	wait1Msec(50);
	SensorMode[S1] = modeEV3Color_Color;
	wait1Msec(50);

	SensorType[S2] = sensorEV3_Gyro;
	wait1Msec(50);
	SensorMode[S2] = modeEV3Gyro_Calibration;
	wait1Msec(100);
	SensorMode[S2] = modeEV3Gyro_RateAndAngle;
	wait1Msec(50);

	SensorType[S3] = sensorEV3_Ultrasonic;

	SensorType[S4] = sensorEV3_IRSensor;
	wait1Msec(50);
	//SensorMode[S4] = modeEV3IR_Calibration;
	//wait1Msec(100);
	//SensorMode[S4] = modeEV3IR_Seeker;
	SensorMode[S4] = modeEV3IR_Remote;
	wait1Msec(1000);

}

const int TABLE1_RANGE = 8;
const int TABLE2_RANGE = -9;

int locateTable()
{

	int table_number = 0;

	if(getIRBeaconDirection(S4) >= TABLE1_RANGE)
		table_number = 1;

	else if(getIRBeaconDirection(S4) >= TABLE2_RANGE)
		table_number = 2;

	else
		table_number = 3;

	return table_number;
}

task main()
{
	configureAllSensors();
	// int table_number = locateTable();
	for(int count = 0; count < 100; count++)
	{
	displayString(3, "Table Number %d", getIRBeaconDirection(S4));
	wait1Msec(1000);
	}
}